version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper'
    container_name: zookeeper_KafkaTraining01
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka_KafkaTraining01
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
#  kafka1:
#    image: 'bitnami/kafka:latest'
#    container_name: kafka_KafkaTraining02
#    ports:
#      - '9093:9092'
#    environment:
#      - KAFKA_BROKER_ID=2
#      - KAFKA_LISTENERS=PLAINTEXT://:9093
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper